### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [pushkarydv/anomm#4]
Hello there!

I would like to work on the README.md file of this repo to make it more appealing!!

I would be sending a PR if approved with my changes

**Comment by pushkarydv** [comment]
Yes Atharva, you can make any changes and create a pr.

**Comment by pushkarydv** [comment]
PR Merged⚡
`made some chages as screenshots are intentionaly made to bottom.`

help us grow by sharing on social media 
[Tweet Template](http://twitter.com/share?text=Anomm%20is%20a%20free%20service%20to%20deliver%20anonymous%20messages%20directly%20to%20your%20telegram.%20%0Ahttps%3A%2F%2Fanomm.pushkaryadav.in)
